// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

#if os(macOS)
  import AppKit
#elseif os(iOS)
  import UIKit
#elseif os(tvOS) || os(watchOS)
  import UIKit
#endif

// Deprecated typealiases
@available(*, deprecated, renamed: "ColorAsset.Color", message: "This typealias will be removed in SwiftGen 7.0")
internal typealias AssetColorTypeAlias = ColorAsset.Color
@available(*, deprecated, renamed: "ImageAsset.Image", message: "This typealias will be removed in SwiftGen 7.0")
internal typealias AssetImageTypeAlias = ImageAsset.Image

// swiftlint:disable superfluous_disable_command file_length implicit_return

// MARK: - Asset Catalogs

// swiftlint:disable identifier_name line_length nesting type_body_length type_name
internal enum Asset {
  internal static let blackSegment = ColorAsset(name: "blackSegment")
  internal static let detail = ColorAsset(name: "detail")
  internal static let primary = ColorAsset(name: "primary")
  internal static let secondary = ColorAsset(name: "secondary")
  internal static let tertiary = ColorAsset(name: "tertiary")
  internal static let text = ColorAsset(name: "text")
  internal static let text2 = ColorAsset(name: "text2")
  internal static let _0Front = ImageAsset(name: "0_front")
  internal static let abecasia = ImageAsset(name: "abecasia")
  internal static let afeganistao = ImageAsset(name: "afeganistao")
  internal static let africadosul = ImageAsset(name: "africadosul")
  internal static let albania = ImageAsset(name: "albania")
  internal static let alemanha = ImageAsset(name: "alemanha")
  internal static let andorra = ImageAsset(name: "andorra")
  internal static let angola = ImageAsset(name: "angola")
  internal static let antiguaebarbuda = ImageAsset(name: "antiguaebarbuda")
  internal static let arabiasaudita = ImageAsset(name: "arabiasaudita")
  internal static let argelia = ImageAsset(name: "argelia")
  internal static let argentina = ImageAsset(name: "argentina")
  internal static let armenia = ImageAsset(name: "armenia")
  internal static let australia = ImageAsset(name: "australia")
  internal static let austria = ImageAsset(name: "austria")
  internal static let azerbaijao = ImageAsset(name: "azerbaijao")
  internal static let bahamas = ImageAsset(name: "bahamas")
  internal static let bahrein = ImageAsset(name: "bahrein")
  internal static let bangladesh = ImageAsset(name: "bangladesh")
  internal static let barbados = ImageAsset(name: "barbados")
  internal static let belarus = ImageAsset(name: "belarus")
  internal static let belgica = ImageAsset(name: "belgica")
  internal static let belize = ImageAsset(name: "belize")
  internal static let benim = ImageAsset(name: "benim")
  internal static let bolivia = ImageAsset(name: "bolivia")
  internal static let bosniaeherzegovina = ImageAsset(name: "bosniaeherzegovina")
  internal static let botsuana = ImageAsset(name: "botsuana")
  internal static let brasil = ImageAsset(name: "brasil")
  internal static let brunei = ImageAsset(name: "brunei")
  internal static let bulgaria = ImageAsset(name: "bulgaria")
  internal static let burkinafaso = ImageAsset(name: "burkinafaso")
  internal static let burundi = ImageAsset(name: "burundi")
  internal static let butao = ImageAsset(name: "butao")
  internal static let caboverde = ImageAsset(name: "caboverde")
  internal static let camaroes = ImageAsset(name: "camaroes")
  internal static let camboja = ImageAsset(name: "camboja")
  internal static let canada = ImageAsset(name: "canada")
  internal static let catar = ImageAsset(name: "catar")
  internal static let cazaquistao = ImageAsset(name: "cazaquistao")
  internal static let chade = ImageAsset(name: "chade")
  internal static let chile = ImageAsset(name: "chile")
  internal static let china = ImageAsset(name: "china")
  internal static let chipre = ImageAsset(name: "chipre")
  internal static let colombia = ImageAsset(name: "colombia")
  internal static let comores = ImageAsset(name: "comores")
  internal static let congo = ImageAsset(name: "congo")
  internal static let coreiadonorte = ImageAsset(name: "coreiadonorte")
  internal static let coreiadosul = ImageAsset(name: "coreiadosul")
  internal static let costadomarfim = ImageAsset(name: "costadomarfim")
  internal static let costarica = ImageAsset(name: "costarica")
  internal static let croacia = ImageAsset(name: "croacia")
  internal static let cuba = ImageAsset(name: "cuba")
  internal static let dinamarca = ImageAsset(name: "dinamarca")
  internal static let djibouti = ImageAsset(name: "djibouti")
  internal static let dominica = ImageAsset(name: "dominica")
  internal static let egito = ImageAsset(name: "egito")
  internal static let elsalvador = ImageAsset(name: "elsalvador")
  internal static let emiradosarabesunidos = ImageAsset(name: "emiradosarabesunidos")
  internal static let equador = ImageAsset(name: "equador")
  internal static let eritreia = ImageAsset(name: "eritreia")
  internal static let escocia = ImageAsset(name: "escocia")
  internal static let eslovaquia = ImageAsset(name: "eslovaquia")
  internal static let eslovenia = ImageAsset(name: "eslovenia")
  internal static let espanha = ImageAsset(name: "espanha")
  internal static let estadosunidos = ImageAsset(name: "estadosunidos")
  internal static let estonia = ImageAsset(name: "estonia")
  internal static let eswatini = ImageAsset(name: "eswatini")
  internal static let etiopia = ImageAsset(name: "etiopia")
  internal static let fiji = ImageAsset(name: "fiji")
  internal static let filipinas = ImageAsset(name: "filipinas")
  internal static let finlandia = ImageAsset(name: "finlandia")
  internal static let franca = ImageAsset(name: "franca")
  internal static let gabao = ImageAsset(name: "gabao")
  internal static let gambia = ImageAsset(name: "gambia")
  internal static let gana = ImageAsset(name: "gana")
  internal static let georgia = ImageAsset(name: "georgia")
  internal static let granada = ImageAsset(name: "granada")
  internal static let grecia = ImageAsset(name: "grecia")
  internal static let guatemala = ImageAsset(name: "guatemala")
  internal static let guiana = ImageAsset(name: "guiana")
  internal static let guianafrancesa = ImageAsset(name: "guianafrancesa")
  internal static let guineBissau = ImageAsset(name: "guine-bissau")
  internal static let guine = ImageAsset(name: "guine")
  internal static let guineequatorial = ImageAsset(name: "guineequatorial")
  internal static let haiti = ImageAsset(name: "haiti")
  internal static let holanda = ImageAsset(name: "holanda")
  internal static let honduras = ImageAsset(name: "honduras")
  internal static let hungria = ImageAsset(name: "hungria")
  internal static let iemen = ImageAsset(name: "iemen")
  internal static let ilhasmarshall = ImageAsset(name: "ilhasmarshall")
  internal static let ilhassalomao = ImageAsset(name: "ilhassalomao")
  internal static let india = ImageAsset(name: "india")
  internal static let indonesia = ImageAsset(name: "indonesia")
  internal static let inglaterra = ImageAsset(name: "inglaterra")
  internal static let ira = ImageAsset(name: "ira")
  internal static let iraque = ImageAsset(name: "iraque")
  internal static let irlanda = ImageAsset(name: "irlanda")
  internal static let irlandadonorte = ImageAsset(name: "irlandadonorte")
  internal static let islandia = ImageAsset(name: "islandia")
  internal static let israel = ImageAsset(name: "israel")
  internal static let italia = ImageAsset(name: "italia")
  internal static let jamaica = ImageAsset(name: "jamaica")
  internal static let japao = ImageAsset(name: "japao")
  internal static let jordania = ImageAsset(name: "jordania")
  internal static let kiribati = ImageAsset(name: "kiribati")
  internal static let kosovo = ImageAsset(name: "kosovo")
  internal static let kuwait = ImageAsset(name: "kuwait")
  internal static let laos = ImageAsset(name: "laos")
  internal static let lesoto = ImageAsset(name: "lesoto")
  internal static let letonia = ImageAsset(name: "letonia")
  internal static let libano = ImageAsset(name: "libano")
  internal static let liberia = ImageAsset(name: "liberia")
  internal static let libia = ImageAsset(name: "libia")
  internal static let liechtenstein = ImageAsset(name: "liechtenstein")
  internal static let lituania = ImageAsset(name: "lituania")
  internal static let luxemburgo = ImageAsset(name: "luxemburgo")
  internal static let macedonia = ImageAsset(name: "macedonia")
  internal static let madagascar = ImageAsset(name: "madagascar")
  internal static let malasia = ImageAsset(name: "malasia")
  internal static let malaui = ImageAsset(name: "malaui")
  internal static let maldivas = ImageAsset(name: "maldivas")
  internal static let mali = ImageAsset(name: "mali")
  internal static let malta = ImageAsset(name: "malta")
  internal static let marrocos = ImageAsset(name: "marrocos")
  internal static let mauricio = ImageAsset(name: "mauricio")
  internal static let mauritania = ImageAsset(name: "mauritania")
  internal static let mexico = ImageAsset(name: "mexico")
  internal static let micronesia = ImageAsset(name: "micronesia")
  internal static let mocambique = ImageAsset(name: "mocambique")
  internal static let moldova = ImageAsset(name: "moldova")
  internal static let monaco = ImageAsset(name: "monaco")
  internal static let mongolia = ImageAsset(name: "mongolia")
  internal static let montenegro = ImageAsset(name: "montenegro")
  internal static let myanmar = ImageAsset(name: "myanmar")
  internal static let namibia = ImageAsset(name: "namibia")
  internal static let nauru = ImageAsset(name: "nauru")
  internal static let nepal = ImageAsset(name: "nepal")
  internal static let nicaragua = ImageAsset(name: "nicaragua")
  internal static let niger = ImageAsset(name: "niger")
  internal static let nigeria = ImageAsset(name: "nigeria")
  internal static let noruega = ImageAsset(name: "noruega")
  internal static let novazelandia = ImageAsset(name: "novazelandia")
  internal static let oma = ImageAsset(name: "oma")
  internal static let ossetiadosul = ImageAsset(name: "ossetiadosul")
  internal static let paisdegales = ImageAsset(name: "paisdegales")
  internal static let paisesbaixos = ImageAsset(name: "paisesbaixos")
  internal static let palau = ImageAsset(name: "palau")
  internal static let palestina = ImageAsset(name: "palestina")
  internal static let panama = ImageAsset(name: "panama")
  internal static let papuaNovaguine = ImageAsset(name: "papua-novaguine")
  internal static let paquistao = ImageAsset(name: "paquistao")
  internal static let paraguai = ImageAsset(name: "paraguai")
  internal static let peru = ImageAsset(name: "peru")
  internal static let polonia = ImageAsset(name: "polonia")
  internal static let portugal = ImageAsset(name: "portugal")
  internal static let quenia = ImageAsset(name: "quenia")
  internal static let quirguistao = ImageAsset(name: "quirguistao")
  internal static let reinounido = ImageAsset(name: "reinounido")
  internal static let republicaarabesaarauidemocratica = ImageAsset(name: "republicaarabesaarauidemocratica")
  internal static let republicacentroAfricana = ImageAsset(name: "republicacentro-africana")
  internal static let republicademocraticadocongo = ImageAsset(name: "republicademocraticadocongo")
  internal static let republicadominicana = ImageAsset(name: "republicadominicana")
  internal static let republicatcheca = ImageAsset(name: "republicatcheca")
  internal static let republicaturcadechipredonorte = ImageAsset(name: "republicaturcadechipredonorte")
  internal static let romenia = ImageAsset(name: "romenia")
  internal static let ruanda = ImageAsset(name: "ruanda")
  internal static let russia = ImageAsset(name: "russia")
  internal static let samoa = ImageAsset(name: "samoa")
  internal static let sanmarino = ImageAsset(name: "sanmarino")
  internal static let santalucia = ImageAsset(name: "santalucia")
  internal static let saocristovaoenevis = ImageAsset(name: "saocristovaoenevis")
  internal static let saotomeeprincipe = ImageAsset(name: "saotomeeprincipe")
  internal static let saovicenteegranadinas = ImageAsset(name: "saovicenteegranadinas")
  internal static let seicheles = ImageAsset(name: "seicheles")
  internal static let senegal = ImageAsset(name: "senegal")
  internal static let serraleoa = ImageAsset(name: "serraleoa")
  internal static let servia = ImageAsset(name: "servia")
  internal static let singapura = ImageAsset(name: "singapura")
  internal static let siria = ImageAsset(name: "siria")
  internal static let somalia = ImageAsset(name: "somalia")
  internal static let srilanka = ImageAsset(name: "srilanka")
  internal static let sudao = ImageAsset(name: "sudao")
  internal static let sudaodosul = ImageAsset(name: "sudaodosul")
  internal static let suecia = ImageAsset(name: "suecia")
  internal static let suica = ImageAsset(name: "suica")
  internal static let suriname = ImageAsset(name: "suriname")
  internal static let tadjiquistao = ImageAsset(name: "tadjiquistao")
  internal static let tailandia = ImageAsset(name: "tailandia")
  internal static let taiwan = ImageAsset(name: "taiwan")
  internal static let tanzania = ImageAsset(name: "tanzania")
  internal static let timorleste = ImageAsset(name: "timorleste")
  internal static let togo = ImageAsset(name: "togo")
  internal static let tonga = ImageAsset(name: "tonga")
  internal static let trinidadetobago = ImageAsset(name: "trinidadetobago")
  internal static let tunisia = ImageAsset(name: "tunisia")
  internal static let turcomenistao = ImageAsset(name: "turcomenistao")
  internal static let turquia = ImageAsset(name: "turquia")
  internal static let tuvalu = ImageAsset(name: "tuvalu")
  internal static let ucrania = ImageAsset(name: "ucrania")
  internal static let uganda = ImageAsset(name: "uganda")
  internal static let uruguai = ImageAsset(name: "uruguai")
  internal static let uzbequistao = ImageAsset(name: "uzbequistao")
  internal static let vanuatu = ImageAsset(name: "vanuatu")
  internal static let vaticano = ImageAsset(name: "vaticano")
  internal static let venezuela = ImageAsset(name: "venezuela")
  internal static let vietna = ImageAsset(name: "vietna")
  internal static let zambia = ImageAsset(name: "zambia")
  internal static let zimbabue = ImageAsset(name: "zimbabue")
  internal static let buttonArrow = ImageAsset(name: "buttonArrow")
  internal static let destinosTabIcon = ImageAsset(name: "destinosTabIcon")
  internal static let destinosTabIconActived = ImageAsset(name: "destinosTabIconActived")
  internal static let doubleCheck = ImageAsset(name: "doubleCheck")
  internal static let explorarTabIcon = ImageAsset(name: "explorarTabIcon")
  internal static let explorarTabIconActived = ImageAsset(name: "explorarTabIconActived")
  internal static let heartIcon = ImageAsset(name: "heartIcon")
  internal static let homeImage = ImageAsset(name: "homeImage")
  internal static let selectedHeartIcon = ImageAsset(name: "selectedHeartIcon")
  internal static let shareIcon = ImageAsset(name: "shareIcon")
  internal static let usrIMG = ImageAsset(name: "usrIMG")
  internal static let afeganistao0 = ImageAsset(name: "afeganistao0")
  internal static let africadosul0 = ImageAsset(name: "africadosul0")
  internal static let albania0 = ImageAsset(name: "albania0")
  internal static let alemanha0 = ImageAsset(name: "alemanha0")
  internal static let andorra0 = ImageAsset(name: "andorra0")
  internal static let angola0 = ImageAsset(name: "angola0")
  internal static let antiguaebarbuda0 = ImageAsset(name: "antiguaebarbuda0")
  internal static let arabiasaudita0 = ImageAsset(name: "arabiasaudita0")
  internal static let argelia0 = ImageAsset(name: "argelia0")
  internal static let argentina0 = ImageAsset(name: "argentina0")
  internal static let armenia0 = ImageAsset(name: "armenia0")
  internal static let australia0 = ImageAsset(name: "australia0")
  internal static let austria0 = ImageAsset(name: "austria0")
  internal static let azerbaijao0 = ImageAsset(name: "azerbaijao0")
  internal static let bahamas0 = ImageAsset(name: "bahamas0")
  internal static let bahrein0 = ImageAsset(name: "bahrein0")
  internal static let bangladesh0 = ImageAsset(name: "bangladesh0")
  internal static let barbados0 = ImageAsset(name: "barbados0")
  internal static let belarus0 = ImageAsset(name: "belarus0")
  internal static let belgica0 = ImageAsset(name: "belgica0")
  internal static let belize0 = ImageAsset(name: "belize0")
  internal static let benim0 = ImageAsset(name: "benim0")
  internal static let bolivia0 = ImageAsset(name: "bolivia0")
  internal static let bosniaeherzegovina0 = ImageAsset(name: "bosniaeherzegovina0")
  internal static let botsuana0 = ImageAsset(name: "botsuana0")
  internal static let brunei0 = ImageAsset(name: "brunei0")
  internal static let bulgaria0 = ImageAsset(name: "bulgaria0")
  internal static let burkinafaso0 = ImageAsset(name: "burkinafaso0")
  internal static let burundi0 = ImageAsset(name: "burundi0")
  internal static let butao0 = ImageAsset(name: "butao0")
  internal static let caboverde0 = ImageAsset(name: "caboverde0")
  internal static let camaroes0 = ImageAsset(name: "camaroes0")
  internal static let camboja0 = ImageAsset(name: "camboja0")
  internal static let canada0 = ImageAsset(name: "canada0")
  internal static let catar0 = ImageAsset(name: "catar0")
  internal static let cazaquistao0 = ImageAsset(name: "cazaquistao0")
  internal static let chade0 = ImageAsset(name: "chade0")
  internal static let chile0 = ImageAsset(name: "chile0")
  internal static let china0 = ImageAsset(name: "china0")
  internal static let chipre0 = ImageAsset(name: "chipre0")
  internal static let colombia0 = ImageAsset(name: "colombia0")
  internal static let comores0 = ImageAsset(name: "comores0")
  internal static let coreiadonorte0 = ImageAsset(name: "coreiadonorte0")
  internal static let coreiadosul0 = ImageAsset(name: "coreiadosul0")
  internal static let costadomarfim0 = ImageAsset(name: "costadomarfim0")
  internal static let costarica0 = ImageAsset(name: "costarica0")
  internal static let croacia0 = ImageAsset(name: "croacia0")
  internal static let cuba0 = ImageAsset(name: "cuba0")
  internal static let dinamarca0 = ImageAsset(name: "dinamarca0")
  internal static let djibouti0 = ImageAsset(name: "djibouti0")
  internal static let dominica0 = ImageAsset(name: "dominica0")
  internal static let egito0 = ImageAsset(name: "egito0")
  internal static let elsalvador0 = ImageAsset(name: "elsalvador0")
  internal static let emiradosarabesunidos0 = ImageAsset(name: "emiradosarabesunidos0")
  internal static let equador0 = ImageAsset(name: "equador0")
  internal static let eritreia0 = ImageAsset(name: "eritreia0")
  internal static let eslovaquia0 = ImageAsset(name: "eslovaquia0")
  internal static let eslovenia0 = ImageAsset(name: "eslovenia0")
  internal static let espanha0 = ImageAsset(name: "espanha0")
  internal static let estadosunidos0 = ImageAsset(name: "estadosunidos0")
  internal static let estonia0 = ImageAsset(name: "estonia0")
  internal static let eswatini0 = ImageAsset(name: "eswatini0")
  internal static let etiopia0 = ImageAsset(name: "etiopia0")
  internal static let fiji0 = ImageAsset(name: "fiji0")
  internal static let filipinas0 = ImageAsset(name: "filipinas0")
  internal static let finlandia0 = ImageAsset(name: "finlandia0")
  internal static let franca0 = ImageAsset(name: "franca0")
  internal static let gabao0 = ImageAsset(name: "gabao0")
  internal static let gambia0 = ImageAsset(name: "gambia0")
  internal static let gana0 = ImageAsset(name: "gana0")
  internal static let georgia0 = ImageAsset(name: "georgia0")
  internal static let granada0 = ImageAsset(name: "granada0")
  internal static let grecia0 = ImageAsset(name: "grecia0")
  internal static let guatemala0 = ImageAsset(name: "guatemala0")
  internal static let guiana0 = ImageAsset(name: "guiana0")
  internal static let guianafrancesa0 = ImageAsset(name: "guianafrancesa0")
  internal static let guineBissau0 = ImageAsset(name: "guine-bissau0")
  internal static let guine0 = ImageAsset(name: "guine0")
  internal static let guineequatorial0 = ImageAsset(name: "guineequatorial0")
  internal static let haiti0 = ImageAsset(name: "haiti0")
  internal static let holanda0 = ImageAsset(name: "holanda0")
  internal static let honduras0 = ImageAsset(name: "honduras0")
  internal static let hungria0 = ImageAsset(name: "hungria0")
  internal static let iemen0 = ImageAsset(name: "iemen0")
  internal static let ilhasmarshall0 = ImageAsset(name: "ilhasmarshall0")
  internal static let ilhassalomao0 = ImageAsset(name: "ilhassalomao0")
  internal static let india0 = ImageAsset(name: "india0")
  internal static let indonesia0 = ImageAsset(name: "indonesia0")
  internal static let ira0 = ImageAsset(name: "ira0")
  internal static let iraque0 = ImageAsset(name: "iraque0")
  internal static let irlanda0 = ImageAsset(name: "irlanda0")
  internal static let islandia0 = ImageAsset(name: "islandia0")
  internal static let israel0 = ImageAsset(name: "israel0")
  internal static let italia0 = ImageAsset(name: "italia0")
  internal static let jamaica0 = ImageAsset(name: "jamaica0")
  internal static let japao0 = ImageAsset(name: "japao0")
  internal static let jordania0 = ImageAsset(name: "jordania0")
  internal static let kiribati0 = ImageAsset(name: "kiribati0")
  internal static let kuwait0 = ImageAsset(name: "kuwait0")
  internal static let laos0 = ImageAsset(name: "laos0")
  internal static let lesoto0 = ImageAsset(name: "lesoto0")
  internal static let letonia0 = ImageAsset(name: "letonia0")
  internal static let libano0 = ImageAsset(name: "libano0")
  internal static let liberia0 = ImageAsset(name: "liberia0")
  internal static let libia0 = ImageAsset(name: "libia0")
  internal static let liechtenstein0 = ImageAsset(name: "liechtenstein0")
  internal static let lituania0 = ImageAsset(name: "lituania0")
  internal static let luxemburgo0 = ImageAsset(name: "luxemburgo0")
  internal static let macedonia0 = ImageAsset(name: "macedonia0")
  internal static let madagascar0 = ImageAsset(name: "madagascar0")
  internal static let malasia0 = ImageAsset(name: "malasia0")
  internal static let malaui0 = ImageAsset(name: "malaui0")
  internal static let maldivas0 = ImageAsset(name: "maldivas0")
  internal static let mali0 = ImageAsset(name: "mali0")
  internal static let malta0 = ImageAsset(name: "malta0")
  internal static let marrocos0 = ImageAsset(name: "marrocos0")
  internal static let mauricio0 = ImageAsset(name: "mauricio0")
  internal static let mauritania0 = ImageAsset(name: "mauritania0")
  internal static let mexico0 = ImageAsset(name: "mexico0")
  internal static let micronesia0 = ImageAsset(name: "micronesia0")
  internal static let mocambique0 = ImageAsset(name: "mocambique0")
  internal static let moldova0 = ImageAsset(name: "moldova0")
  internal static let monaco0 = ImageAsset(name: "monaco0")
  internal static let mongolia0 = ImageAsset(name: "mongolia0")
  internal static let montenegro0 = ImageAsset(name: "montenegro0")
  internal static let myanmar0 = ImageAsset(name: "myanmar0")
  internal static let namibia0 = ImageAsset(name: "namibia0")
  internal static let nauru0 = ImageAsset(name: "nauru0")
  internal static let nepal0 = ImageAsset(name: "nepal0")
  internal static let nicaragua0 = ImageAsset(name: "nicaragua0")
  internal static let niger0 = ImageAsset(name: "niger0")
  internal static let nigeria0 = ImageAsset(name: "nigeria0")
  internal static let noruega0 = ImageAsset(name: "noruega0")
  internal static let novazelandia0 = ImageAsset(name: "novazelandia0")
  internal static let oma0 = ImageAsset(name: "oma0")
  internal static let palau0 = ImageAsset(name: "palau0")
  internal static let palestina0 = ImageAsset(name: "palestina0")
  internal static let panama0 = ImageAsset(name: "panama0")
  internal static let papuaNovaguine0 = ImageAsset(name: "papua-novaguine0")
  internal static let paquistao0 = ImageAsset(name: "paquistao0")
  internal static let paraguai0 = ImageAsset(name: "paraguai0")
  internal static let peru0 = ImageAsset(name: "peru0")
  internal static let polonia0 = ImageAsset(name: "polonia0")
  internal static let portorico0 = ImageAsset(name: "portorico0")
  internal static let portugal0 = ImageAsset(name: "portugal0")
  internal static let quenia0 = ImageAsset(name: "quenia0")
  internal static let quirguistao0 = ImageAsset(name: "quirguistao0")
  internal static let reinounido0 = ImageAsset(name: "reinounido0")
  internal static let republicacentroAfricana0 = ImageAsset(name: "republicacentro-africana0")
  internal static let republicademocraticadocongo0 = ImageAsset(name: "republicademocraticadocongo0")
  internal static let republicadocongo0 = ImageAsset(name: "republicadocongo0")
  internal static let republicadominicana0 = ImageAsset(name: "republicadominicana0")
  internal static let republicatcheca0 = ImageAsset(name: "republicatcheca0")
  internal static let romenia0 = ImageAsset(name: "romenia0")
  internal static let ruanda0 = ImageAsset(name: "ruanda0")
  internal static let russia0 = ImageAsset(name: "russia0")
  internal static let samoa0 = ImageAsset(name: "samoa0")
  internal static let sanmarino0 = ImageAsset(name: "sanmarino0")
  internal static let santalucia0 = ImageAsset(name: "santalucia0")
  internal static let saocristovaoenevis0 = ImageAsset(name: "saocristovaoenevis0")
  internal static let saotomeeprincipe0 = ImageAsset(name: "saotomeeprincipe0")
  internal static let saovicenteegranadinas0 = ImageAsset(name: "saovicenteegranadinas0")
  internal static let seicheles0 = ImageAsset(name: "seicheles0")
  internal static let senegal0 = ImageAsset(name: "senegal0")
  internal static let serraleoa0 = ImageAsset(name: "serraleoa0")
  internal static let servia0 = ImageAsset(name: "servia0")
  internal static let singapura0 = ImageAsset(name: "singapura0")
  internal static let siria0 = ImageAsset(name: "siria0")
  internal static let somalia0 = ImageAsset(name: "somalia0")
  internal static let srilanka0 = ImageAsset(name: "srilanka0")
  internal static let sudao0 = ImageAsset(name: "sudao0")
  internal static let sudaodosul0 = ImageAsset(name: "sudaodosul0")
  internal static let suecia0 = ImageAsset(name: "suecia0")
  internal static let suica0 = ImageAsset(name: "suica0")
  internal static let suriname0 = ImageAsset(name: "suriname0")
  internal static let tadjiquistao0 = ImageAsset(name: "tadjiquistao0")
  internal static let tailandia0 = ImageAsset(name: "tailandia0")
  internal static let taiwanChina0 = ImageAsset(name: "taiwan(china)0")
  internal static let tanzania0 = ImageAsset(name: "tanzania0")
  internal static let timorleste0 = ImageAsset(name: "timorleste0")
  internal static let togo0 = ImageAsset(name: "togo0")
  internal static let trinidadetobago0 = ImageAsset(name: "trinidadetobago0")
  internal static let tunisia0 = ImageAsset(name: "tunisia0")
  internal static let turcomenistao0 = ImageAsset(name: "turcomenistao0")
  internal static let turquia0 = ImageAsset(name: "turquia0")
  internal static let tuvalu0 = ImageAsset(name: "tuvalu0")
  internal static let ucrania0 = ImageAsset(name: "ucrania0")
  internal static let uganda0 = ImageAsset(name: "uganda0")
  internal static let uruguai0 = ImageAsset(name: "uruguai0")
  internal static let uzbequistao0 = ImageAsset(name: "uzbequistao0")
  internal static let vaticano0 = ImageAsset(name: "vaticano0")
  internal static let venezuela0 = ImageAsset(name: "venezuela0")
  internal static let vietna0 = ImageAsset(name: "vietna0")
  internal static let zambia0 = ImageAsset(name: "zambia0")
  internal static let zimbabue0 = ImageAsset(name: "zimbabue0")
  internal static let launchMock = ImageAsset(name: "launchMock")
}
// swiftlint:enable identifier_name line_length nesting type_body_length type_name

// MARK: - Implementation Details

internal final class ColorAsset {
  internal fileprivate(set) var name: String

  #if os(macOS)
  internal typealias Color = NSColor
  #elseif os(iOS) || os(tvOS) || os(watchOS)
  internal typealias Color = UIColor
  #endif

  @available(iOS 11.0, tvOS 11.0, watchOS 4.0, macOS 10.13, *)
  internal private(set) lazy var color: Color = {
    guard let color = Color(asset: self) else {
      fatalError("Unable to load color asset named \(name).")
    }
    return color
  }()

  fileprivate init(name: String) {
    self.name = name
  }
}

internal extension ColorAsset.Color {
  @available(iOS 11.0, tvOS 11.0, watchOS 4.0, macOS 10.13, *)
  convenience init?(asset: ColorAsset) {
    let bundle = BundleToken.bundle
    #if os(iOS) || os(tvOS)
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(macOS)
    self.init(named: NSColor.Name(asset.name), bundle: bundle)
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

internal struct ImageAsset {
  internal fileprivate(set) var name: String

  #if os(macOS)
  internal typealias Image = NSImage
  #elseif os(iOS) || os(tvOS) || os(watchOS)
  internal typealias Image = UIImage
  #endif

  internal var image: Image {
    let bundle = BundleToken.bundle
    #if os(iOS) || os(tvOS)
    let image = Image(named: name, in: bundle, compatibleWith: nil)
    #elseif os(macOS)
    let name = NSImage.Name(self.name)
    let image = (bundle == .main) ? NSImage(named: name) : bundle.image(forResource: name)
    #elseif os(watchOS)
    let image = Image(named: name)
    #endif
    guard let result = image else {
      fatalError("Unable to load image asset named \(name).")
    }
    return result
  }
}

internal extension ImageAsset.Image {
  @available(macOS, deprecated,
    message: "This initializer is unsafe on macOS, please use the ImageAsset.image property")
  convenience init?(asset: ImageAsset) {
    #if os(iOS) || os(tvOS)
    let bundle = BundleToken.bundle
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(macOS)
    self.init(named: NSImage.Name(asset.name))
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

// swiftlint:disable convenience_type
private final class BundleToken {
  static let bundle: Bundle = {
    #if SWIFT_PACKAGE
    return Bundle.module
    #else
    return Bundle(for: BundleToken.self)
    #endif
  }()
}
// swiftlint:enable convenience_type
